version: '3.4'

services:
  postgres:
    image: postgres
    container_name: postgres
    hostname: postgres
    restart: always
    networks:
      - internal
    ports:
      - 5432:5432
    expose:
      - 5432
    env_file:
      - ./.env
    volumes:
      - postgres:/var/lib/postgresql/data
  cloudflared:
    image: cloudflare/cloudflared:latest #update the verion where necessary
    container_name: cloudflared
    restart: always
    networks:
      - internal
    command: tunnel --no-autoupdate run --token eyJhIjoiZWQ2NmE1NDZlYWVhMWNlMDBlYjE2YmI1Yzc1NmFkY2EiLCJ0IjoiYzI2MmFhYTYtOTVkYi00YzE5LTk4NzktZTI2YzMwMTg1YmU4IiwicyI6IllUQmhOelk0WkRJdE5HVTNZeTAwTjJZeUxUaGxOVEF0TVRVd1l6WTBNakpqWWpreCJ9
  mongo:
    image: mongo
    hostname: mongo
    container_name: mongo
    networks:
      - internal
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: cachorro_cami
      MONGO_INITDB_ROOT_PASSWORD: Tengo1amo

  mongo-express:
    image: mongo-express
    restart: always
    networks:
      - internal
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: cachorro_cami
      ME_CONFIG_MONGODB_ADMINPASSWORD: Tengo1amo
      ME_CONFIG_MONGODB_URL: mongodb://cachorro_cami:Tengo1amo@mongo:27017/

  app:
    image: app
    hostname: app
    restart: always
    depends_on:
      - postgres
    container_name: app
    build:
      context: ./
      dockerfile: prod.Dockerfile
      args:
        BASE_URL: 'https://app.rsasesorjuridico.com'
        URL: ${URL}
        HOST: ${HOST}
        MONGODB_URI: ${MONGODB_URI}
        PORT: ${PORT}
        NODE_ENV: ${NODE_ENV}
    env_file: .env
    environment:
      PORT: 3000
      MONGODB_URI: mongodb+srv://cachorro_cami:Tengo1amo@cluster0.ffbyjzl.mongodb.net/?retryWrites=true&w=majority
      NODE_ENV: production
    ports:
      - 5555:3000
    expose:
      - 3000
    networks:
      - internal

volumes:
  postgres:
networks:
  internal:
    external: true
    name: internal
