import './globals.css';
import { Inter } from 'next/font/google';
import type { Metadata } from 'next';
import Script from 'next/script';
import {
  inter,
  josefina,
  poiret,
  raleway,
  roboto,
} from '#@/styles/fonts/fonts';
import { getBaseUrl } from '#@/lib/getBaseUrl';
import { ReactNode } from 'react';



export const metadata: Metadata = {
  metadataBase: new URL(
    'https://app.rsasesorjuridico.com'
  ),
  title: 'R&S Asesoría Jurídica',
  description: 'Generated by create next app',
  generator: 'R&S Asesoría Jurídica',
  applicationName: 'R&S Asesoría Jurídica',
  referrer: 'origin-when-cross-origin',
  keywords: [
    'Next.js',
    'React',
    'JavaScript'
  ],
  authors: [
    {
      name: 'cam',
    },
    {
      name: 'Cachorro Cami',
      url: 'https://app.rsasesorjuridico.com',
    },
  ],
  colorScheme: 'light dark',
  themeColor: [
    {
      media: '(prefers-color-scheme: light)',
      color: '#bb152c',
    },
    {
      media: '(prefers-color-scheme: dark)',
      color: '#ab2a64',
    },
  ],
  creator: 'Cachorro Cami',
  manifest: 'https://app.rsasesorjuridico.com/manifest.webmanifest',
  publisher: 'CachorroC',
  alternates: {},
  formatDetection: {
    email: false,
    address: false,
    telephone: false,
  },
  openGraph: {
    title: 'R&S Asesoría Jurídica',
    description: 'The React Framework for the Web',
    url: 'https://app.rsasesorjuridico.com',
    siteName: 'Next.js',
    images: [
      {
        url: 'https://app.rsasesorjuridico.com/splash_screens/12.9__iPad_Pro_portrait.png',
        width: 800,
        height: 600,
      },
      {
        url: 'https://app.rsasesorjuridico.com / splash_screens /8.3__iPad_Mini_landscape.png',
        width: 1800,
        height: 1600,
        alt: 'My custom alt',
      },
    ],
    locale: 'es-CO',
    type: 'website',
  },
  icons: {
    icon: [
      {
        url: '/icons/favicon.png',
      },
      new URL(
        '/favicon.svg',
        'https://app.rsasesorjuridico.com'
      ),
    ],
    shortcut: '/safari-pinned-tab.svg',
    apple: '/icons/apple-touch-icon.png',
    other: {
      rel: 'apple-touch-icon-precomposed',
      url: '/icons/apple-touch-icon-precomposed.png',
    },
  },
  appleWebApp: {
    title: 'Apple Web App',
    statusBarStyle: 'black-translucent',
    startupImage: [
      '/icons/mstile-310x310.png',
      {
        url: '/icons/android-chrome-512x512.png',
        media: '(device-width: 768px) and (device-height: 1024px)',
      },
    ],
  },
  appLinks: {
    web: {
      url: 'https://app.rsasesorjuridico.com',
      should_fallback: true,
    },
  },
};

export default function RootLayout(
  {
    children,modal
  }: {
      children: ReactNode; modal: ReactNode
}
) {
  return (
    <html lang="en">
      <body className={ `${ poiret.variable } ${ raleway.variable } ${ inter.variable } ${ roboto.variable } ${ josefina.variable } [ color-scheme: light dark ]` }>
        {modal}
        { children }
        <Script src={ `${ getBaseUrl() }/service-worker.js` } />
      </body>
    </html>
  );
}
